In [2]:
from nltk.corpus import gutenberg  # Import the gutenberg corpus from NLTK
import nltk  # Import the NLTK library
nltk.download('gutenberg')  # Download the gutenberg corpus
gutenberg.fileids()  # List file-ids in the corpus

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\QianZ\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [4]:
print("Chars\tWords\tSents\tFile")
for fileid in gutenberg.fileids(): # Iterate through files in corpus
    num_chars = len(gutenberg.raw(fileid))
    num_words = len(gutenberg.words(fileid))
    num_sents = len(gutenberg.sents(fileid))
    print("%7.0f\t%7.0f\t%7.0f\t%s" % (num_sents,num_words,num_chars,fileid))

Chars	Words	Sents	File
   7752	 192427	 887071	austen-emma.txt
   3747	  98171	 466292	austen-persuasion.txt
   4999	 141576	 673022	austen-sense.txt
  30103	1010654	4332554	bible-kjv.txt
    438	   8354	  38153	blake-poems.txt
   2863	  55563	 249439	bryant-stories.txt
   1054	  18963	  84663	burgess-busterbrown.txt
   1703	  34110	 144395	carroll-alice.txt
   4779	  96996	 457450	chesterton-ball.txt
   3806	  86063	 406629	chesterton-brown.txt
   3742	  69213	 320525	chesterton-thursday.txt
  10230	 210663	 935158	edgeworth-parents.txt
  10059	 260819	1242990	melville-moby_dick.txt
   1851	  96825	 468220	milton-paradise.txt
   2163	  25833	 112310	shakespeare-caesar.txt
   3106	  37360	 162881	shakespeare-hamlet.txt
   1907	  23140	 100351	shakespeare-macbeth.txt
   4250	 154883	 711215	whitman-leaves.txt


In [6]:
from nltk import word_tokenize  # Importtheword_tokenizefunctionfromNLTK
from string import punctuation
punctuation_list = list(punctuation)  # Convertstringwithpunctuationmarkstolist
text = "The new table is red. The blue table is broken."
text_tokens_processed = []
text_tokens = word_tokenize(text)  # Tokenisethetextintowords
for token in text_tokens:  # Iteratethroughtheavailabletokens
    if token not in punctuation_list:  # Omittokensthatarepunctuationmarks
        # Addlowercaseversionoftokentolist
        text_tokens_processed.append(token.lower())
print("List of processed words:", text_tokens_processed)

Listofprocessedwords: ['the', 'new', 'table', 'is', 'red', 'the', 'blue', 'table', 'is', 'broken']


In [7]:
vocabulary = set()  # Createanemptyset
for word in text_tokens_processed:  # Iteratethroughavailablewords
    vocabulary.add(word)  # Addwordtoset

print("Vocabulary:", vocabulary)
print("Vocabularysize:", len(vocabulary))
vocabulary2 = set(text_tokens_processed)
print("\nVocabulary2:", vocabulary2)
print("Vocabulary2size:", len(vocabulary2))

Vocabulary: {'the', 'new', 'red', 'table', 'is', 'broken', 'blue'}
Vocabularysize: 7

Vocabulary2: {'the', 'new', 'red', 'table', 'is', 'broken', 'blue'}
Vocabulary2size: 7


In [8]:
for fileid in gutenberg.fileids():  # Iterate through documents in corpus
    vocabulary_of_document = set()  # Create empty set
    for word in gutenberg.words(fileid):  # Iterate through words in document
        if word not in punctuation_list:  # Omit tokens that are punctuation marks
            vocabulary_of_document.add(word.lower())
    print("%6.0f\t%s" % (len(vocabulary_of_document), fileid))

  7328	austen-emma.txt
  5820	austen-persuasion.txt
  6388	austen-sense.txt
 12755	bible-kjv.txt
  1521	blake-poems.txt
  3925	bryant-stories.txt
  1547	burgess-busterbrown.txt
  2622	carroll-alice.txt
  8313	chesterton-ball.txt
  7780	chesterton-brown.txt
  6335	chesterton-thursday.txt
  8432	edgeworth-parents.txt
 17215	melville-moby_dick.txt
  9007	milton-paradise.txt
  3019	shakespeare-caesar.txt
  4703	shakespeare-hamlet.txt
  3451	shakespeare-macbeth.txt
 12437	whitman-leaves.txt


In [11]:
vocabulary_of_corpus = set() # Create empty set

for fileid in gutenberg.fileids(): # Iterate through documents in corpus
    for word in gutenberg.words(fileid): # Iterate through words in document
        if word not in punctuation_list: # Omit tokens that are punctuation marks
            vocabulary_of_corpus.add(word.lower())

print("Vocabulary of Gutenberg corpus:",len(vocabulary_of_corpus),"words")

Vocabulary of Gutenberg corpus: 42314 words


In [12]:
from numpy import array  # Import array type from numpy
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
vocabulary = ['is', 'table', 'blue', 'red', 'broken', 'new', 'the']
# Convert to array because it is required by the LabelEncoder() object
data = array(vocabulary)
print(data, "\n")
# Integer encoding- Assigns a unique index to each unique word
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded, "\n")
# One-Hot encoding- Assigns a One-Hot binary representation to each word
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded, "\n")
for i in range(len(data)):
    print(onehot_encoded[i], "->", data[i])

['is' 'table' 'blue' 'red' 'broken' 'new' 'the'] 

[2 5 0 4 1 3 6] 

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]] 

[0. 0. 1. 0. 0. 0. 0.] -> is
[0. 0. 0. 0. 0. 1. 0.] -> table
[1. 0. 0. 0. 0. 0. 0.] -> blue
[0. 0. 0. 0. 1. 0. 0.] -> red
[0. 1. 0. 0. 0. 0. 0.] -> broken
[0. 0. 0. 1. 0. 0. 0.] -> new
[0. 0. 0. 0. 0. 0. 1.] -> the


In [13]:
dictionary = {}
for i in range(len(data)):
    dictionary[data[i]] = onehot_encoded[i]

print(dictionary)
print("\nred =",dictionary['red'])

{'is': array([0., 0., 1., 0., 0., 0., 0.]), 'table': array([0., 0., 0., 0., 0., 1., 0.]), 'blue': array([1., 0., 0., 0., 0., 0., 0.]), 'red': array([0., 0., 0., 0., 1., 0., 0.]), 'broken': array([0., 1., 0., 0., 0., 0., 0.]), 'new': array([0., 0., 0., 1., 0., 0., 0.]), 'the': array([0., 0., 0., 0., 0., 0., 1.])}

red = [0. 0. 0. 0. 1. 0. 0.]


In [15]:
def get_label_from_dictionary(dictionary, value):
    for word, one_hot in dictionary.items():  # Iterate all pairs (word, one-hot representation) in the dictionary
        if (one_hot == value).all():  # Compare equality between numpy arrays
            return word


print(get_label_from_dictionary(dictionary, [0, 0, 0, 0, 1, 0, 0]))

red


In [16]:
from numpy import logical_or # Import the element-wise logical OR function from numpy
from numpy import zeros # Import the zeros function from numpy
text = "The new table is red. The blue table is broken."
print("List of processed words:",text_tokens_processed)
result = zeros(len(dictionary)) # Start from zero-valued vector- Convert to numpy array
for word in text_tokens_processed: # Iterate words in text
    print(result.astype(int), "OR", dictionary[word],"= ",end='')
    result = logical_or(result,dictionary[word]) # Compute the element-wise logical or between the partial result and the one-hot representation of the word
    print(result.astype(int))
print("\nOne-Hot encoded text:",result.astype(int))

List of processed words: ['the', 'new', 'table', 'is', 'red', 'the', 'blue', 'table', 'is', 'broken']
[0 0 0 0 0 0 0] OR [0. 0. 0. 0. 0. 0. 1.] = [0 0 0 0 0 0 1]
[0 0 0 0 0 0 1] OR [0. 0. 0. 1. 0. 0. 0.] = [0 0 0 1 0 0 1]
[0 0 0 1 0 0 1] OR [0. 0. 0. 0. 0. 1. 0.] = [0 0 0 1 0 1 1]
[0 0 0 1 0 1 1] OR [0. 0. 1. 0. 0. 0. 0.] = [0 0 1 1 0 1 1]
[0 0 1 1 0 1 1] OR [0. 0. 0. 0. 1. 0. 0.] = [0 0 1 1 1 1 1]
[0 0 1 1 1 1 1] OR [0. 0. 0. 0. 0. 0. 1.] = [0 0 1 1 1 1 1]
[0 0 1 1 1 1 1] OR [1. 0. 0. 0. 0. 0. 0.] = [1 0 1 1 1 1 1]
[1 0 1 1 1 1 1] OR [0. 0. 0. 0. 0. 1. 0.] = [1 0 1 1 1 1 1]
[1 0 1 1 1 1 1] OR [0. 0. 1. 0. 0. 0. 0.] = [1 0 1 1 1 1 1]
[1 0 1 1 1 1 1] OR [0. 1. 0. 0. 0. 0. 0.] = [1 1 1 1 1 1 1]

One-Hot encoded text: [1 1 1 1 1 1 1]


In [17]:
def get_text_one_hot_encoding(words_list, dictionary):
    # Start from zero-valued vector-Convert to numpy array
    result = zeros(len(dictionary))
    for word in words_list:  # Iterate words in text
        # Compute the element-wise logical or between the partial result and the one-hot representation of the word
        result = logical_or(result, dictionary[word])
    return result.astype(int)


words_list = ['the', 'broken', 'table']
print("\nOne-Hot encoded text:", get_text_one_hot_encoding(words_list, dictionary))


One-Hot encoded text: [0 1 0 0 0 1 1]


In [18]:
from nltk import FreqDist  # Import the FreqDist function from NLTK
text = "The new table is red. The blue table is broken."
text_tokens_processed = ['the', 'new', 'table', 'is',
                         'red', 'the', 'blue', 'table', 'is', 'broken']
vocabulary = {'new', 'broken', 'the', 'blue', 'table', 'red', 'is'}
tf = FreqDist(text_tokens_processed)  # Compute term frequency of words
print(tf, "\n")
vocabulary = sorted(vocabulary)  # Sort alphabetiacally for better presentation
for word in vocabulary:
    print("%5.0f %s" % (tf[word], word))

<FreqDist with 7 samples and 10 outcomes> 

    1 blue
    1 broken
    2 is
    1 new
    1 red
    2 table
    2 the


In [19]:
text_tf = []
for word in vocabulary:
    text_tf.append(tf[word])
print(text_tf, "->", text)
text2 = "The new table is broken"
text2_tokens_processed = ['the', 'new', 'table', 'is', 'broken']
tf2 = FreqDist(text2_tokens_processed)  # Compute term frequency of words
text2_tf = []
for word in vocabulary:
    text2_tf.append(tf2[word])
print(text2_tf, "->", text2)

[1, 1, 2, 1, 1, 2, 2] -> The new table is red. The blue table is broken.
[0, 1, 1, 1, 0, 1, 1] -> The new table is broken


In [20]:
# Create a list of the lists of lowercase words without punctuation marks for each document
texts_words_processed = []
texts_words_processed.append(
    ['the', 'new', 'table', 'is', 'red', 'the', 'blue', 'table', 'was', 'broken'])
texts_words_processed.append(
    ['the', 'new', 'movie', 'that', 'we', 'watched', 'yesterday', 'was', 'terrible'])
texts_words_processed.append(
    ['we', 'raised', 'the', 'red', 'and', 'blue', 'flag', 'yesterday'])
print(texts_words_processed)
# Create the vocabulary
vocabulary_texts = set()
for doc in texts_words_processed:
    for word in doc:
        vocabulary_texts.add(word)
# Sort vocabulary alphabetically for better presentation
vocabulary_texts = sorted(vocabulary_texts)
print("\nVocabulary:", vocabulary_texts)
DF = dict()  # Create an empty dictionary
for word in vocabulary_texts:  # Iterate through words in vocabulary
    cnt = 0
    for doc in texts_words_processed:  # Iterate through documents
        if word in doc:
            cnt += 1  # cnt += 1 is equal to cnt = cnt + 1
    DF[word] = cnt
print("\nDocument frequencies:", DF)

[['the', 'new', 'table', 'is', 'red', 'the', 'blue', 'table', 'was', 'broken'], ['the', 'new', 'movie', 'that', 'we', 'watched', 'yesterday', 'was', 'terrible'], ['we', 'raised', 'the', 'red', 'and', 'blue', 'flag', 'yesterday']]

Vocabulary: ['and', 'blue', 'broken', 'flag', 'is', 'movie', 'new', 'raised', 'red', 'table', 'terrible', 'that', 'the', 'was', 'watched', 'we', 'yesterday']

Document frequencies: {'and': 1, 'blue': 2, 'broken': 1, 'flag': 1, 'is': 1, 'movie': 1, 'new': 2, 'raised': 1, 'red': 2, 'table': 1, 'terrible': 1, 'that': 1, 'the': 3, 'was': 2, 'watched': 1, 'we': 2, 'yesterday': 2}


### Inverse Document Frequency

$ IDF(t,D) = \log (\frac{N}{DF(t,d)}) $

In [21]:
import math  # Import math library
N = 3  # The corpus contains 3 documents
IDF = dict()  # Create an empty dictionary
for word in vocabulary_texts:  # Iterate through words in vocabulary
    IDF[word] = math.log(N / DF[word])  # Compute IDF of word
print("IDF:", IDF)

IDF: {'and': 1.0986122886681098, 'blue': 0.4054651081081644, 'broken': 1.0986122886681098, 'flag': 1.0986122886681098, 'is': 1.0986122886681098, 'movie': 1.0986122886681098, 'new': 0.4054651081081644, 'raised': 1.0986122886681098, 'red': 0.4054651081081644, 'table': 1.0986122886681098, 'terrible': 1.0986122886681098, 'that': 1.0986122886681098, 'the': 0.0, 'was': 0.4054651081081644, 'watched': 1.0986122886681098, 'we': 0.4054651081081644, 'yesterday': 0.4054651081081644}


### Term Frequency- Inverse Document Frequency (TF-IDF)

$ TFIDF(t,d,D) = TF(t,d) \times IDF(t,D) $

In [22]:
from nltk import FreqDist  # Import the FreqDist function from NLTK
TF = []
for doc in texts_words_processed:  # Iterate though documents
    TF.append(FreqDist(doc))  # Compute word frequency
print(TF, "\n")
TFIDF = []
for tf_doc in TF:
    tfidf_doc = dict()
    for word in vocabulary_texts:  # Iterate through words in vocabulary
        # Compute TF-IDF- tf_doc is of type FreqDist and will return 0 for words that don't exist
        tfidf_doc[word] = tf_doc[word] * IDF[word]
        TFIDF.append(tfidf_doc)
cnt = 0
for tfidf_doc in TFIDF:
    print("Text", cnt, "TF-IDF:", tfidf_doc, "\n")
    cnt += 1

[FreqDist({'the': 2, 'table': 2, 'new': 1, 'is': 1, 'red': 1, 'blue': 1, 'was': 1, 'broken': 1}), FreqDist({'the': 1, 'new': 1, 'movie': 1, 'that': 1, 'we': 1, 'watched': 1, 'yesterday': 1, 'was': 1, 'terrible': 1}), FreqDist({'we': 1, 'raised': 1, 'the': 1, 'red': 1, 'and': 1, 'blue': 1, 'flag': 1, 'yesterday': 1})] 

Text 0 TF-IDF: {'and': 0.0, 'blue': 0.4054651081081644, 'broken': 1.0986122886681098, 'flag': 0.0, 'is': 1.0986122886681098, 'movie': 0.0, 'new': 0.4054651081081644, 'raised': 0.0, 'red': 0.4054651081081644, 'table': 2.1972245773362196, 'terrible': 0.0, 'that': 0.0, 'the': 0.0, 'was': 0.4054651081081644, 'watched': 0.0, 'we': 0.0, 'yesterday': 0.0} 

Text 1 TF-IDF: {'and': 0.0, 'blue': 0.4054651081081644, 'broken': 1.0986122886681098, 'flag': 0.0, 'is': 1.0986122886681098, 'movie': 0.0, 'new': 0.4054651081081644, 'raised': 0.0, 'red': 0.4054651081081644, 'table': 2.1972245773362196, 'terrible': 0.0, 'that': 0.0, 'the': 0.0, 'was': 0.4054651081081644, 'watched': 0.0, 'we'